name: zetexa_assignment
description: "flutter assignment for Zetexa Global."

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  responsive_sizer: ^3.2.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.2.4
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
